# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    container_name: stack-appfall-db
    image: lagmoellertim/appfall-db:1.1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  backend:
    container_name: stack-appfall-backend
    image: lagmoellertim/appfall-backend:1.5
    environment:
      - DB_HOST=stack-appfall-db
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
  frontend:
    container_name: stack-appfall-frontend
    image: lagmoellertim/appfall-frontend:1.2
    environment:
      - HOST=localhost:8000
    ports:
      - 5173:5173